### ISSUE TITLE
luvit.io and lit.luvit.io are down

### ISSUE THREAD

**Issue by PhoenixShay** [luvit/luvit.io#18]
Title

**Comment by creationix** [comment]
@rphillips 

Since luvit.io is basically a static site, I've made a static copy of it and stored it at `/home/lit/static/luvit.io/`.  The old `luvit.io` systemd service is now disabled and nginx serves the static assets directly instead of proxying to luvit.

This should help some with the instability.  One of the problematic processes is gone and there is more memory for the other one.
